### ISSUE TITLE
Buttons for any User-defined macros

### ISSUE THREAD

**Issue by EagleB3** [jneilliii/OctoPrint-BedLevelVisualizer#166]
Please offer on the plugin’s tab, somewhere close to the “Update” button, 
1..3..5 buttons on which user can assign a macro as you wish.
If in the settings it will be possible to set the behavior of the button 
- hidden permanently (if not used),
- hidden (or inaccessible) during the printing process, 
- hidden (or inaccessible) during the bedleveling process,
the solution will be universal (f.e. see issue #156).

Someone will be able to assign BL-Touch sensor control commands to these buttons (lower / raise the probe), someone will reset the printer.
Personally, I really do not have enough buttons to send the M374 command to save the table created by the well-doned bed level adjustment in the controller's memory.

**Comment by LMS0815** [comment]
I have the same issue. 
As a workaround, I am using OctoPrint "Custom Control Editor" to create those missing buttons.

**Comment by jneilliii** [comment]
So i have made some headway into getting this feature implemented.  If you'd like to test it out for me that would be great.  You can install my latest development version by using the URL below in Plugin Manager.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.12.zip

![image](https://user-images.githubusercontent.com/5249455/72689358-a09cc200-3ade-11ea-8af6-9be94e57db1b.png)

![image](https://user-images.githubusercontent.com/5249455/72689369-b7dbaf80-3ade-11ea-8ae1-73924fe265b6.png)

**Comment by EagleB3** [comment]
Yesterday I started testing the new version. Just in case, I’ll say that I installed the modified plugin by simply unpacking the files from the ZIP archive and replacing the existing files in the plugins directory with Raspberry.

So far so good! Excellent functionality, very convenient to use! You even made pictograms on the buttons - **EXCELLENT**!
I have not found any errors in the work, I will continue testing.

And, I think it will be very useful to add the ability **to assign Hint** for this buttons (pop-up 
tooltip) to the interface. This can probably be done something like this:
![With_Hint](https://user-images.githubusercontent.com/43371261/72780895-11ec8a00-3c31-11ea-9338-701541697134.png)
Probably, the maximum number of characters in such a hint should be limited by some reasonable number (50? 100? 255?).

It seems to me that adding such an opportunity is not difficult, and with it the functionality will become absolutely universal.

Thank you for your work!

P.S. Thank you separately for the button icons. I saw your screenshots with pictograms on the Octoprint tabs ("Temperature", "Control", "Video"...) and I really liked it. But I could not understand how this can be done.

**Comment by jneilliii** [comment]
The tooltip is set on the buttons and should be popping up the gcode commands, iis that not enough? 

My TabOrder plugin allows for setting the icons on the tabs.

**Comment by EagleB3** [comment]
The fact that you did pop-up G-codes is very good. It is wonderful! Let them pop up if the user has not set their own Hint for the button.
You have made excellent universal buttons that can send not only the "M119" command to the terminal, but also a sequence of commands. It’s not convenient to parse a long sequence, Hint is more convenient
One person can program the button, and another can use it, still less familiar with G-codes.
It will be possible to make small-sized buttons, with only one icon, and at the same time having good information content. The script from the screenshot works great on the button you made. But it will be much better if not the full G-Code pops up, but the phrase "**Define Z0 for print begin**"
By the way, the script in the popup field did not fit all. The last two characters did not fit, they are not visible.
![sample](https://user-images.githubusercontent.com/43371261/72828052-edbe9680-3c8c-11ea-8711-0ae6d0b899bb.png)
Therefore, I believe that such a hint is advisable.

This is a higher level of ergonomics. Higher level of service for the user. This is a programming culture. We must strive for this.

But of course, this is just IMHO. You certainly have already done a very good job. Thanks!

**Comment by jneilliii** [comment]
Ok, you make a good point, but this is not my job, I make very very little on the tips I get via PayPal relative to the time I put into making changes and implementing feature  requests. 

BTW, you should be able to enter the commands with returns instead of the | symbol since I converted it to a text area.

**Comment by jneilliii** [comment]
Slightly changed the layout. Made a little more sense putting the tooltip option on the same line as the icon, label options as they're all related to the button itself.  That allows for a larger area for the command field. I've just pushed an update to the same branch that incorporates the option.  

![image](https://user-images.githubusercontent.com/5249455/72865713-d55b7580-3ca6-11ea-9a35-7b8202201f47.png)

![image](https://user-images.githubusercontent.com/5249455/72865826-37b47600-3ca7-11ea-942a-b2c1123ef48c.png)

![image](https://user-images.githubusercontent.com/5249455/72865859-59156200-3ca7-11ea-8ecb-bee8ab27d895.png)

**Warning on installing this update**.  Either delete all your custom commands prior to upgrading or manually modify your config.yaml adding a `tooltip` field to each custom command like below to either what you want your tooltip to be, blank,  or `null`.

```
plugins:
  bedlevelvisualizer:
    commands:
    - command: '@BEDLEVELVISUALIZER

        M117 Label 1 Clicked'
      enabled_while_graphing: false
      enabled_while_printing: true
      icon: fas fa-archive
      label: Label 1
      tooltip: Update Mesh Data
    - command: M117 Label 2 Clicked
      enabled_while_graphing: true
      enabled_while_printing: false
      icon: fas fa-expand-arrows-alt
      label: Label 2
      tooltip: 
    - command: M117 Label 3 Clicked
      enabled_while_graphing: true
      enabled_while_printing: false
      icon: far fa-angry
      label: Label 3
      tooltip: null
```
