### ISSUE TITLE
Updating mesh from printer clears all custom system actions defined in config.yaml

### ISSUE THREAD

**Issue by ghost** [jneilliii/OctoPrint-BedLevelVisualizer#228]
When the "Update mesh now" button is clicked, it clears all custom actions under the **system** section of config.yaml after updating the mesh.

Steps to reproduce:
1. Click "Update mesh now".
2. Refresh OctoPrint's UI.
3. Check config.yaml see any custom actions defined under the **system** section disappear. Instead you see **system: {}**.

Octoprint version: 1.4.0
BedLevelVisualizer version: 0.1.13 (latest)

**Comment by jneilliii** [comment]
Can you provide an example custom system command you had configured? Also, are you using a plugin to set those or manually adding in config.yaml?

**Comment by ghost** [comment]
I have tried using the System Command Editor (https://plugins.octoprint.org/plugins/systemcommandeditor/) and tried editing config.yaml manually to create two actions. Both times, updating the mesh clears the custom actions. The actions are:

```
system:
    actions:
    -   action: poweron
        command: gpio -1 write 16 1
        confirm: false
        name: Power on printer
    -   action: poweroff
        command: gpio -1 write 16 0
        confirm: This will turn off the connected 3D printer.
        name: Power off printer
```

I use these actions to turn my 3d printer on and off using the telegram bot and as an alternative to PSU Control from the **Power** menu in Octoprint.

Ignore the incorrect indentation. I can't seem to get it right.

**Comment by jneilliii** [comment]
Thanks, I'll do some testing on my end and try to find out what's going on. No worries on the formatting, I fixed it up for you.

**Comment by jneilliii** [comment]
This appears to be an issue reported a while back on the System Command Editor plugin's repo over [here](https://github.com/Salandora/OctoPrint-SystemCommandEditor/issues/5) with other user's reporting the same thing.  The last couple of reports are from user's that were seeing it with Bed Visualizer. Does it also happen if you disable System Command Editor completely and manually update the system commands?

**Comment by ghost** [comment]
My troubleshooting steps involved the following:
1. Both **Bed Visualizer** and **System Command Editor** installed.
2. Custom system commands defined.
3. Updated mesh.
4. Lost custom system commands.
5. Re-defined custom system commands using **System Command Editor**.
6. Updated mesh.
7. Lost custom system commands.
8. Uninstalled **System Command Editor**.
9. Restarted OctoPrint.
10. SSH'd into OctoPrint and defined custom system actions in config.yaml.
11. Updated mesh.
12. Lost custom system actions.
13. Uninstalled **BedVisualizer**.
14. Restarted OctoPrint.
15. Confirmed custom system actions persist across server restarts and reboots.

I hope this makes sense.

**Comment by jneilliii** [comment]
Ok, just did some testing on my development machine and the commands don't appear to be deleting falling these steps.

1. Uninstall System Command Editor
2. SSH to the Pi
3. Run command `sudo service octoprint stop`
4. update config.yaml with your commands. For my testing since I'm on windows I modified to open notepad and calc for the two commands.
```
system:
    actions:
    -   action: poweron
        command: notepad.exe
        confirm: false
        name: Power on printer
    -   action: poweroff
        command: calc.exe
        confirm: This will turn off the connected 3D printer.
        name: Power off printer
```
5. run command: `sudo service octoprint start`
6. Open web page, update mesh: no changes to system commands
7. restart OctoPrint: no changes to system commands
8. Update mesh: no changes to system commands

I'm about to test on a pi to verify these steps on it as well, but wanted to give you my initial findings.
