### ISSUE TITLE
[REQUEST] Improved axis accuracy

### ISSUE THREAD

**Issue by mylife4aiurr** [jneilliii/OctoPrint-BedLevelVisualizer#28]
Its hard to interpret delta (circle) data in Cartesian (rectangle) format.
should be a circle
0,0 as center of data points
x/y scale should reflect delta radius or printable radius
z scale lowest to highest probed points

http://forums.reprap.org/read.php?178,477060
![b699d0309431d21056f97824ac_800x400](https://user-images.githubusercontent.com/31583073/39097240-a47c6482-4627-11e8-95e8-8e39f1e7303e.jpg)

If its too much work to make a specific view model for delta's let me know (your sweat)
Just saying as is its more suited for prusa i3 style printers

**Comment by jneilliii** [comment]
duplicate of #20 I'm close to getting one that works for all.

**Comment by mylife4aiurr** [comment]
I was trying to break up the issues.
1 issue for if data is displayed to user - cartesian or delta
1 issue for how data is displayed for delta user

**Comment by jneilliii** [comment]
I understand now.  Correct, display at all vs display as round surface for delta.

**Comment by jneilliii** [comment]
> General for delta, not just mine.
> Pull data from Topography Report
> (0,9)        (9,9)
> (-98,98) **_min_**    (98,98)  **_max_**
> that will have actual ranges
> -(1/2min)  x(0)  +(1/2max)
> -(1/2min)  y(0)  +(1/2max)
> 
> what do you think?

Let's keep them separate.  Here's your last post relative to the graphing issue.  I don't quite understand what you mean. I'm not really great with the Math involved with this. I do think I can get it to work once we can get the data in a format that plotly can interpret.  May have to use a different type of 3d graph like a 3D scatter plot.

https://plot.ly/javascript/3d-scatter-plots/

or possibly tri-surf

https://plot.ly/javascript/trisurf/

**Comment by jneilliii** [comment]
I was able to move the axis on plotly create to shift by adding X and Y.

![image](https://user-images.githubusercontent.com/5249455/39099258-8d9d113a-4645-11e8-95a2-3f38fca8a25c.png)

but the visual representation of the data is still skewed.

**Comment by mylife4aiurr** [comment]
ok thanks for separating issues.
Im hoping to have the ranges used for delta printers be more representative of their actual bed dimensions. for a delta is double radius or bed diameter or printable area. So how does one get that range to show in a graph??
your pluggin pulls the bed dimensions when it pulls the topography report:
(0,9)                                                                   (9,9)
(-98,98)                                                              (98,98)

Im asking that the pulled bed data be actual the x and y range for the graph shown.
So in above example 
-1/2(98) = min x range graphical 
1/2(98) = max x range graphical
so the x range:
-49 -40 -30 -20 -10 x 10 20 40 49

-1/2(98) = min y range graphical 
1/2(98) = max y range graphical
so the y range:
-49 -40 -30 -20 -10 x 10 20 40 49

by definition a circle will have same radius all around, really no need to do calculations for x and y separately.
 
so maybe 1/2 of whatever largest number, maybe quick dirty way to get xy range to display on graph
(0,9)                                                                   (9,9)
(-98,98)                                                              (98,98)

but the main point I'm trying to get across is having 0,0 center of graph like actual bed, like pic above in 1st post this issue.

**Comment by jneilliii** [comment]
I think our posts may have crossed, So axis like in above screenshot I just posted?

**Comment by jneilliii** [comment]
I realize it's not the actual dimensions, but at least is showing the probe points relative to center axis the same as with the cartesian one.  I've been wanting to add more accurate representation of those anyway, so this would definitely need to be accounted for.

**Comment by mylife4aiurr** [comment]
thats better then b4. glad 0,0 is center of graph, better than 0,0 lower left like cartesian
 

but why ranges 
x -4 to 4
y -4 to 4

**Comment by jneilliii** [comment]
That's how plotly interprets it for some reason.  The cartesian one does similar, if you supply 10 points it shows 9x9.

**Comment by mylife4aiurr** [comment]
ok ok i understand.... not trying to add extra work for u. 

you are trying to use same model for both kinds of printers, i get it

**Comment by mylife4aiurr** [comment]
so bed size isnt passed to plotly? only plotted points?

**Comment by jneilliii** [comment]
Exactly, plotly interprets those, I just pass it an array.

**Comment by jneilliii** [comment]
But I'm only passing the z coordinates, not the x and y.  That was going to be my next phase of revisions, pulling the dimensions from OctoPrint printer profile configuration and supplying it points based on the size of the array of points from the data collection.

**Comment by mylife4aiurr** [comment]
well ok there u go...... :)

**Comment by jneilliii** [comment]
Can you send me a screenshot of what you printer profile in OctoPrint looks like?

**Comment by jneilliii** [comment]
For the build volume section.

**Comment by mylife4aiurr** [comment]
![delta printer profile](https://user-images.githubusercontent.com/31583073/39099433-2c5af050-4649-11e8-9d8e-2ab999762949.jpg)

**Comment by mylife4aiurr** [comment]
Seems topography report pulls radius.... which would need to be doubled

But its cool if you can pull dimensions from Octoprint also

**Comment by ajanky** [comment]
just a short note here: if you read the bed dimensions from the Octo profile, what about scaling the Z axis relative to bed size: I (feel) the z-error representation is too dramatic, since it always scales to full range, even if the max error is very little.

**Comment by token47** [comment]
As I said on #34 (now closed), it would be great to have Z scale fixed (and configurable, maybe). This is the text from the other bug:

"I noticed that as I try to level the bed, the inclination on screen always stays the same, and what changes is the scale on the Z axis. This is technically correct, but is hard to work with. It would be better if the scale was fixed and you could see the plane changing inclination on the screen until it's horizontal. I suggest a fixed scale of 2mm as a starting point. If my bed is more dis-aligned than that, I wouldn't mind to see parts of graph off screen anyway."

This would be a great addition together with the changes proposed on this one.

**Comment by jneilliii** [comment]
I understand what you mean.  I just did a quick test manually on the plotly site putting in the x and y axis probing points and I think the z axis will naturally scale more appropriately. But with +/-2mm on the z it doesn't look bad, thanks for the suggestion.

![image](https://user-images.githubusercontent.com/5249455/39163147-32d6cd92-4747-11e8-8b7d-a5c53884833d.png)

**Comment by mylife4aiurr** [comment]
I think we are on to something here..... I love the z offset idea. Looks great. Also I noticed  your graph has an actual bed scale that match's your beds length and width. I like 😁

**Comment by jneilliii** [comment]
I agree.  The toss up now is if I fake the probe points just by dividing the bed dimensions by the number of points in the mesh data, or actually pull those from the report. The problem again with the later is dealing with all the different variations of bed leveling reports from the different firmware variants. I think going the lazy programmer route (that's me) of just dividing would be appropriate enough for most people. 

What do you guys think?

**Comment by mylife4aiurr** [comment]
This is your pluggin and your sweat. If you go the lazy route maybe put a disclaimer outlining the reasons the data set is divided so graph and actual bed isnt a 1:1 representation. 
Or force the user to use either human readable or csv so that u cut the variations you have to program for. Or some other criteria that makes less work for you but allows you to use actual data points.

**Comment by mylife4aiurr** [comment]
How does the Delta version looked graphed like that?

**Comment by jneilliii** [comment]
From the previous data this is what the Delta would look like.  I know it's not as smooth as your initial screenshot but definitely is more legible than before.

![image](https://user-images.githubusercontent.com/5249455/39166400-688da158-4757-11e8-935e-fb190056e0b3.png)

**Comment by mylife4aiurr** [comment]
That looks so much better then before, and I feel even though same data it looks closer to reality. Hope I can express my point, but before the z values were so extreme as though - how do you even print on a bed that warped. This version definitely a big improvement.  (I know your working on a circle version for delta)

**Comment by token47** [comment]
> I agree. The toss up now is if I fake the probe points just by dividing the bed dimensions by the number of points in the mesh data, or actually pull those from the report. The problem again with the later is dealing with all the different variations of bed leveling reports from the different firmware variants. I think going the lazy programmer route (that's me) of just dividing would be appropriate enough for most people.
> 
> What do you guys think?
> 

I almost sent you a suggestion about that, then I thought that it would make no difference in practice. The best you can do is work with the points you have, and the graph will represent only that, not the whole bed. You would have to extrapolate and do complicated math that maybe will be a best guess anyway,

**Comment by mylife4aiurr** [comment]
Is there way to represent the unknown region. We know the total bed dimensions from Octoprint profile. We know the area the probe points cover. Can u show unprobed area as grey as in lacking data. If can't visually show an unprobed area, disclaimer that unprobed areas could be lower or higher than probed area. Simply no way to tell. U can imply a tilt based on preceding points but as suggested by token47 that's just a guess at best.

**Comment by jneilliii** [comment]
That type of predictive math on the mesh would be beyond my capabilities I'm afraid. It would also go against the lazy programmer method I'm leaning towards already. I'll probably continue to work on this aspect of the plugin later down the road, but for the initial release of "improved accuracy" I think division of bed size is going to be the fastest approach. I plan on working on it this weekend.

**Comment by jneilliii** [comment]
I just pushed a new branch 0.1.0 with the improved graphing.  I tested with my cartesian and it's working as expected.  I took the lazy programmer route as previously discussed so the points aren't exactly accurate, but I think it's definitely a better representation of the bed overall and gets the point across. 

![image](https://user-images.githubusercontent.com/5249455/39401236-bc190c30-4b0e-11e8-9389-0fef194ffd5e.png)

I tested also by setting by printer profile to circular and it does shift the axis correctly for me, hopefully my math is good enough to work for you real delta guys on here.  Please give it a test and let me know how it goes.

![image](https://user-images.githubusercontent.com/5249455/39401232-8be0b4a0-4b0e-11e8-953e-80936960c804.png)

Install using this url: https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.0.zip

**Comment by mylife4aiurr** [comment]
@jneilliii Glad your still working on this pluggin.
Version 0.1.0 results
Only csv output works for me at this time, yes I did ctrlf5 after install, and I changed appropriate Data Collector Flag between tries.

![unified bed leving before mesh edits_bedlevelvisualizer 0 1 0](https://user-images.githubusercontent.com/31583073/39401530-fb1527e2-4b14-11e8-99ff-252db7006d6b.jpg)

Pic above from ver0.1.0
x axis has 0 in middle. (-80 0 +80) :)
y axis wrong. wanted 0 in middle like x axis :(
z seems to start at 0 as well, I preferred the z at -2 or some negative number to see under bed like b4. :(

**Comment by mylife4aiurr** [comment]
I know you are pulling printer dimensions from Octoprint profile. 
Suggest displaying to delta's differently based on if the form factor is circular in the profile. 
Then Cartesian's would see origin lower left 0,0
Delta's would see center 0,0

**Comment by jneilliii** [comment]
I'll look into the y axis issue.  It should have worked, but I may have gotten the logic wrong. I agree with you, I think the max on z range needs to be lowered instead of the total height of the build volume, the min z range is already set at -2, but because the max is so high it changes the perspective.

**Comment by jneilliii** [comment]
@mylife4aiurr, can you upload your config.yaml settings for this plugin now that you've pulled the data?

**Comment by mylife4aiurr** [comment]
Ok as pointed out in #40....... newest marlins changed how human readable output for M420 V and G29 T looks. So I bet its throwing your interpreter off. csv output is unchanged in newest marlin so it works with your pluggin. Anyone using older marlin versions should be ok with your pluggin, human readable or csv.

So just sayin its not an error with your pluggin rather marlin got updated. You are aware? i think

**Comment by mylife4aiurr** [comment]
yes, I will shortly

**Comment by mylife4aiurr** [comment]
current config.yaml
```
  bedlevelvisualizer:
    command: 'G28

      G29 T1



      '
    mesh_timestamp: 4/28/2018, 6:40:25 PM
    report_flag: 'Bed Topography Report for CSV:'
    save_mesh: false
    stored_mesh:
    - - ''
      - '0.109'
      - '0.018'
      - '-0.037'
      - '-0.032'
      - '-0.000'
      - '0.007'
      - '-0.026'
      - '-0.060'
      - '-0.022'
      - '-0.001'
      - ''
    - - ''
      - '-0.026'
      - '0.003'
      - '-0.032'
      - '-0.054'
      - '-0.011'
      - '0.003'
      - '-0.021'
      - '-0.035'
      - '-0.025'
      - '-0.011'
      - ''
    - - ''
      - '-0.001'
      - '-0.019'
      - '-0.013'
      - '-0.043'
      - '-0.003'
      - '-0.015'
      - '-0.037'
      - '-0.053'
      - '-0.064'
      - '0.015'
      - ''
    - - ''
      - '-0.002'
      - '0.004'
      - '0.012'
      - '-0.013'
      - '0.010'
      - '-0.040'
      - '-0.065'
      - '-0.064'
      - '-0.069'
      - '0.043'
      - ''
    - - ''
      - '0.054'
      - '0.054'
      - '0.010'
      - '-0.000'
      - '-0.022'
      - '-0.057'
      - '-0.078'
      - '-0.061'
      - '-0.058'
      - '0.087'
      - ''
    - - ''
      - '0.179'
      - '0.085'
      - '0.030'
      - '0.005'
      - '-0.019'
      - '-0.040'
      - '-0.051'
      - '-0.030'
      - '0.087'
      - '0.193'
      - ''
    stored_mesh_x:
    - -100
    - -82
    - -64
    - -45
    - -27
    - -9
    - 9
    - 27
    - 45
    - 64
    - 82
    stored_mesh_y:
    - -100
    - -82
    - -64
    - -45
    - -27
    - -9
    - 9
    - 27
    - 45
    - 64
    - 82
```
